routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => 'auth'], function (){
    Route::resource('offer-ride', 'OfferRideController');
    Route::get('get-ride', 'RideController@rides');
    Route::get('ride/{ride_id}', 'RideController@getRide');
    Route::resource('rides', 'RideController');
});

app/User.php
<?php

namespace App;

use Cytonn\Models\OfferRide;
use Cytonn\Models\Ride;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    public function ride()
    {
        return $this->hasMany(Ride::class);
    }

    public function offerRide()
    {
        return $this->hasMany(OfferRide::class);
    }

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Cytonn\Models\OfferRide;
use Cytonn\Models\Ride;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home')
            ->withRides(count(Ride::where('user_id', Auth::user()->id)->get()))
            ->withOffers(count(OfferRide::where('user_id', Auth::user()->id)->get()));
    }
}

app/Http/Controllers/OfferRideController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\OfferRideRequest;
use Cytonn\Models\OfferRide;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Riazxrazor\LaravelSweetAlert\LaravelSweetAlert;

class OfferRideController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('offer-ride.index')
            ->withOffers(OfferRide::with(['rides.user'])->where('user_id', Auth::user()->id)->get());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('offer-ride.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(OfferRideRequest $request)
    {
        //check if the
        $data = $request->all();
        $data['user_id'] = Auth::user()->id;
        $data['status'] = OfferRide::ACTIVE;

        OfferRide::create($data);

        LaravelSweetAlert::setMessageSuccess('Ride added successfully');

        return redirect()->route('offer-ride.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\OfferRide  $offerRide
     * @return \Illuminate\Http\Response
     */
    public function show($offer_id)
    {
        return view('offer-ride.show')
            ->withOffer(OfferRide::with(['rides.user'])->findorfail($offer_id));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\OfferRide  $offerRide
     * @return \Illuminate\Http\Response
     */
    public function edit(OfferRide $offerRide)
    {
        return view('offer-ride.edit')
            ->withOffer($offerRide);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\OfferRide  $offerRide
     * @return \Illuminate\Http\Response
     */
    public function update(OfferRideRequest $request, OfferRide $offerRide)
    {
        $offerRide->update($request->all());

        LaravelSweetAlert::setMessageSuccess('Ride updated successfully');

        return redirect()->route('offer-ride.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\OfferRide  $offerRide
     * @return \Illuminate\Http\Response
     */
    public function destroy(OfferRide $offerRide)
    {
        OfferRide::destroy($offerRide->id);

        LaravelSweetAlert::setMessageSuccess('Ride deleted successfully');

        return redirect()->route('offer-ride.index');
    }
}

app/Http/Controllers/RideController.php
<?php

namespace App\Http\Controllers;


use App\Mail\Shareride;
use App\User;
use Cytonn\Models\OfferRide;
use Cytonn\Models\Ride;
use Cytonn\Repo\RideRepo;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Riazxrazor\LaravelSweetAlert\LaravelSweetAlert;

class RideController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('rides.index')
            ->withRides(Ride::with(['offer.user'])->where('user_id', Auth::user()->id)->get());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Ride  $ride
     * @return \Illuminate\Http\Response
     */
    public function show($offer_id)
    {
        return view('rides.show')
        ->withOffer(OfferRide::with(['rides.user','user'])->findorfail($offer_id));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Ride  $ride
     * @return \Illuminate\Http\Response
     */
    public function edit(Ride $ride)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Ride  $ride
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Ride $ride)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Ride  $ride
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ride $ride)
    {
        $ride->delete();

        LaravelSweetAlert::setMessageSuccess('Ride canceled successfully');

        return redirect()->back();
    }

    public function rides()
    {
        return view('rides.get-rides')
            ->withRides(OfferRide::with(['user','rides'])->where('user_id','!=',Auth::user()->id)
                ->has('user')->get());
    }

    public function getRide($ride_id)
    {
        $check_space = (new RideRepo())->checkCapacity(OfferRide::findorfail($ride_id));

        if ($check_space){

            Ride::create(['offer_ride_id' => $ride_id,'user_id' => Auth::user()->id,'status' =>Ride::ACTIVE]);
            $data['name'] = Auth::user()->name;
            $data['ride_id'] = $ride_id;
            $data['message'] = 'Your ride was successfully booked.';

            Mail::to(Auth::user()->email)->send(new Shareride($data));

            LaravelSweetAlert::setMessageSuccess('Ride booked successfully');

            return redirect()->route('rides.show', $ride_id);
        }

        LaravelSweetAlert::setMessageError('No Space Available');

        return redirect()->back();
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-primary">
                <div class="panel-heading">Welcome {{ Auth::user()->name }}</div>

                <div class="panel-body">
                    <div class="col-sm-6">
                        <div class="well well-lg">
                            <h4 class="text-center">Total Ride Offered <strong>{{ $offers }}</strong></h4>

                            <a href="{{ route('offer-ride.create') }}" class="btn center-block btn-primary"> Offer Ride</a>

                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="well well-lg">
                            <h4 class="text-center">Total Ride Booked <strong>{{ $rides }}</strong></h4>

                            <a href="{{ url('get-ride') }}" class="btn center-block btn-primary"> Get A Ride</a>

                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet">
    @LaravelSweetAlertCSS
</head>
<body>
    <div id="app">
        <nav  class="navbar custom-nav navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a style="color: white" class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">

                        <!-- Authentication Links -->
                        @if (Auth::guest())

                            <li><a href="{{ route('login') }}" class="white-color">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Manage <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{{ url('/home') }}">Dashboard</a></li>
                                    <li><a href="{{ route('rides.index') }}">My Rides</a></li>
                                    <li><a href="{{ route('offer-ride.index') }}">My Offers</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="{{ url('get-ride') }}">Get A Ride</a></li>
                                    <li><a href="{{ route('offer-ride.create') }}">Offer Ride</a></li>

                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu white-color" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    @LaravelSweetAlertJS
</body>
</html>

resources/views/offer-ride/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-primary">
                    <div class="panel-heading">Add Ride</div>

                    <div class="panel-body">
                        <form class="form-horizontal" method="POST" action="{{ route('offer-ride.store') }}">
                            {{ csrf_field() }}

                            <div class="form-group{{ $errors->has('origin') ? ' has-error' : '' }}">
                                <label for="origin" class="col-md-4 control-label">Origin</label>

                                <div class="col-md-6">
                                    <input id="origin" type="text" class="form-control" name="origin" value="{{ old('origin') }}" required autofocus>

                                    @if ($errors->has('origin'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('origin') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('destination') ? ' has-error' : '' }}">
                                <label for="destination" class="col-md-4 control-label">Destination</label>

                                <div class="col-md-6">
                                    <input id="destination" type="text" class="form-control" name="destination" value="{{ old('destination') }}" required>

                                    @if ($errors->has('destination'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('destination') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('capacity') ? ' has-error' : '' }}">
                                <label for="capacity" class="col-md-4 control-label">Vehicle Capacity</label>

                                <div class="col-md-6">
                                    <input id="capacity" type="number" min="1" class="form-control" name="capacity" value="{{ old('capacity') }}" required>

                                    @if ($errors->has('capacity'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('capacity') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <a href="{{ url()->previous() }}" class="btn btn-warning">Back</a>

                                    <button type="submit" class="pull-right btn btn-primary">
                                        Add Ride
                                    </button>
                                </div>
                            </div>
                        </form>

                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/offer-ride/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-primary">
                    <div class="panel-heading">Edit Ride</div>
                    <form class="form-horizontal" method="POST" action="{{ route('offer-ride.update', $offer->id) }}">
                    <div class="panel-body">

                            {{ csrf_field() }}
                            {{method_field('put')}}

                            <div class="form-group{{ $errors->has('origin') ? ' has-error' : '' }}">
                                <label for="origin" class="col-md-4 control-label">Origin</label>

                                <div class="col-md-6">
                                    <input id="origin" type="text" class="form-control" name="origin" value="{{ $offer->origin }}" required autofocus>

                                    @if ($errors->has('origin'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('origin') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('destination') ? ' has-error' : '' }}">
                                <label for="destination" class="col-md-4 control-label">Destination</label>

                                <div class="col-md-6">
                                    <input id="destination" type="text" class="form-control" name="destination" value="{{ $offer->destination }}" required>

                                    @if ($errors->has('destination'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('destination') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('capacity') ? ' has-error' : '' }}">
                                <label for="capacity" class="col-md-4 control-label">Vehicle Capacity</label>

                                <div class="col-md-6">
                                    <input id="capacity" type="number" min="1" class="form-control" name="capacity" value="{{ $offer->capacity }}" required>

                                    @if ($errors->has('capacity'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('capacity') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <a href="{{ url()->previous() }}" class="btn btn-warning">Back</a>

                                    <button type="submit" class="pull-right btn btn-primary">
                                        Edit Ride
                                    </button>
                                </div>
                            </div>
                        </form>

                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/offer-ride/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-md-offset-0">
                <div class="panel panel-primary">
                    <div class="panel-heading clearfix">My Rides
                        <a href="{{ route('offer-ride.create') }}" class="btn pull-right btn-warning">Add Ride</a>
                    </div>

                    <div class="panel-body">
                        <table class="table table-boarded">
                            <thead>
                            <tr>
                                <td>No</td>
                                <td>Origin</td>
                                <td>Destination</td>
                                <td>Capacity</td>
                                <td>Space Available</td>
                                <td>Status</td>
                                <td class="text-center">Action</td>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($offers as $offer)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ ucwords($offer->origin) }}</td>
                                    <td>{{ ucwords($offer->destination) }}</td>
                                    <td>{{ $offer->capacity }}</td>
                                    <td>{{ count($offer->rides) }}</td>
                                    <td>{{ count($offer->rides) >= $offer->capacity ? 'Full' : ucwords($offer->status) }}</td>
                                    <td class="text-center">
                                        <form action="{{ route('offer-ride.destroy', $offer->id) }}" method="post">
                                        <a href="{{ route('offer-ride.edit', $offer->id) }}" class="btn btn-success">Edit</a>
                                        <a href="{{ route('offer-ride.show', $offer->id) }}" class="btn btn-primary">Show</a>
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                            <input type="submit" class="btn btn-danger" value="Delete">
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <a href="{{ url()->previous() }}" class="btn btn-warning">Back</a>

                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/offer-ride/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-primary">
                    <div class="panel-heading clearfix">List of Featured Riders
                        <a href="{{ route('offer-ride.create') }}" class="btn pull-right btn-warning">Offer Ride</a>
                    </div>

                    <div class="panel-body">
                        <div class="col-sm-6"><strong>Driver : </strong> {{ ucwords($offer->user->name) }}</div>
                        <div class="col-sm-6"><strong>Capacity/Space Available : </strong> {{ $offer->capacity }}/{{count($offer->rides)}}</div>
                        <div class="col-sm-6"><strong>Origin : </strong>{{ ucwords($offer->origin) }}</div>
                        <div class="col-sm-6"><strong>Destination : </strong>{{ ucwords($offer->destination) }}</div>
                        <div class="row">
                            <hr>
                        </div>
                        <table class="table table-boarded">
                            <thead>
                            <tr>
                                <td>No</td>
                                <td>Name</td>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($offer->rides as $rider)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ ucwords($rider->user->name) }}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <a href="{{ url()->previous() }}" class="btn btn-warning">Back</a>

                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/rides/get-rides.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-md-offset-0">
                <div class="panel panel-primary">
                    <div class="panel-heading clearfix"><strong>List of Available Rides</strong>
                        <a href="{{ route('offer-ride.create') }}" class="btn pull-right btn-warning">Offer Ride</a>
                    </div>

                    <div class="panel-body">
                        <table class="table table-boarded">
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>Origin</th>
                                <th>Destination</th>
                                <th>Driver</th>
                                <th>Capacity</th>
                                <th>Space Available</th>
                                <th class="text-center">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($rides as $ride)
                                @if($ride->capacity > count($ride->rides))
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ ucwords($ride->origin) }}</td>
                                    <td>{{ ucwords($ride->destination) }}</td>
                                    <td>{{ ucwords($ride->user->name) }}</td>
                                    <td>{{ $ride->capacity }}</td>
                                    <td>{{ count($ride->rides) }}</td>
                                    <td class="text-center">

                                        <a href="{{ url('/ride/'.$ride->id) }}" class="btn btn-success">Get A Ride</a>
                                    </td>
                                </tr>
                                @endif
                            @endforeach
                            </tbody>
                        </table>
                        <a href="{{ url()->previous() }}" class="btn btn-warning">Back</a>

                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/rides/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-md-offset-0">
                <div class="panel panel-primary">
                    <div class="panel-heading clearfix">My Booked Rides
                        <a href="{{ url('/get-ride') }}" class="btn pull-right btn-warning">Get A Ride</a>
                    </div>

                    <div class="panel-body">
                        <table class="table table-boarded">
                            <thead>
                            <tr>
                                <td>No</td>
                                <td>Origin</td>
                                <td>Destination</td>
                                <td>Driver</td>
                                <td class="text-center">Action</td>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($rides as $ride)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ ucwords($ride->offer->origin) }}</td>
                                    <td>{{ ucwords($ride->offer->destination) }}</td>
                                    <td>{{ ucwords($ride->offer->user->name) }}</td>
                                    <td class="text-center">
                                        <form action="{{ route('rides.destroy', $ride->id) }}" method="post">
                                        <a href="{{ route('rides.show', $ride->offer->id) }}" class="btn btn-success">View</a>

                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                            <input type="submit" class="btn btn-danger" value="Cancel">
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <a href="{{ url()->previous() }}" class="btn btn-warning">Back</a>

                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection